const f = require('../config/functions');
var timeDate = f.datetime();
module.exports = {
	pkg: './package.json',
	paths: {
		input: {
			app: './',
			npm: './package',
			nodemon: './node_modules/@seerseven/desmond/src/*.js',
			shopify: './shopify',
			video: 'src/assets/video',
			images: 'src/assets/img',
			shopstart: ['src/build/shopify.js', 'src/build/shopify.css'],
			themstart: ['src/build/theme.js', 'src/build/theme.css'],
			venstart: ['src/build/notion.css', 'src/build/mdb.css'],
			sass: 'src/sass/*.scss',
			schema: 'src/sass/abstracts/utilities/schema/schema.scss',
			cts: 'shopify/assets/*.css',
			files: [
				'src/sass/abstracts/functions/*.scss',
				'!src/sass/abstracts/functions/_index.scss',
			],
			shopifycss: 'src/build/shopify/shopify.css',
			shopifyjs: 'src/build/shopify/shopify.js',
			themecss: 'src/build/theme/theme.css',
			themejs: 'src/build/theme/theme.js',
			mdbcss: 'src/build/vendors/mdb.css',
			notioncss: 'src/build/vendors/notion.css',
			buildcss: [
				'src/dist/shopify.css',
				'src/dist/mdb.css',
				'src/dist/theme.css',
			],
			buildjs: [
				'src/dist/shopify.js',
				'src/dist/core.js',
				'src/dist/concat.js',
				'src/dist/theme.js',
			],
			concatjs: [
				'src/dist/min/query.min.js',
				'src/dist/min/mdb.min.js',
				'src/dist/min/canvas.min.js',
				'src/dist/min/vendor.min.js',
			],
			jsquery: ['src/js/libs/jquery.js', 'src/js/libs/jqueryUI.js'],
			jsmdb: ['src/js/libs/popper.js', 'src/js/libs/mdball.js'],
			jsvendor: [
				'src/js/libs/download.js',
				'src/js/libs/email.js',
				'src/js/libs/vanta.js',
				'src/js/libs/aos.js',
				'src/js/libs/rellax.js',
			],
			jscanvas: [
				'src/js/libs/imagepicker.js',
				'src/js/libs/fabric.js',
				'src/js/libs/three.js',
			],
			jslibs: ['src/dist/canvas.js', 'src/dist/vendor.js'],
			jscore: ['src/dist/query.js', 'src/dist/mdb.js'],
			cleancss: [
				'shopify/assets/*.css',
				'!shopify/assets/*.js',
				'!shopify/assets/desmond.css',
				'!shopify/assets/desmond.min.css',
			],
			cleanjs: [
				'shopify/assets/*.js',
				'!shopify/assets/*.css',
				'!shopify/assets/desmond.js',
				'!shopify/assets/desmond.min.js',
			],
			addall: [
				'./*',
				'!./node_modules/**',
				'!./state/**',
				'!./package-lock.json',
			],
			backup: ['./**/*', './.*/**/*', '!./.git/**', '!./node_modules/**'],
			archive: [
				'./**/*',
				'./.*/**/*',
				'!./.git/**',
				'!./node_modules/**',
				'!./state/**',
			],
			arcproject: [
				'./**/*',
				'./.*/**/*',
				'!./.git/**',
				'!./node_modules/**',
				'!./state/**',
				'!./package/**',
				'!./shopify/themes/**',
			],
			arctheme: ['./shopify/**/*', '!./shopify/themes/**'],
			arcnode: 'package/**/*',
		},
		output: {
			end: 'end',
			app: './',
			npm: './package/src/',
			dist: 'src/dist',
			min: 'src/dist/min',
			libs: 'src/js/libs/',
			parallax: 'parallax/assets',
			shopify: 'shopify/assets',
			schema: 'src/sass/abstracts/utilities/schema',
			sass: 'src/sass',
			cts: 'src/sass/cts',
			scss: 'src/build/scss',
			shopend: 'src/build/shopify',
			themend: 'src/build/theme',
			venend: 'src/build/vendors',
			vault: 'state/archives',
			themevault: 'state/themes',
			multi: ['src/dist', 'shopify/assets'],
			pro: ['parallax/assets', 'shopify/assets'],
		},
		clean: {
			rem: './state/stage/*',
			build: [
				'src/build/**/*',
				'!src/build/shopify/**',
				'!src/build/theme/**',
				'!src/build/vendors/**',
				'!src/build/scss/**',
			],
			min: 'src/dist/min/**/*',
			dist: ['src/dist/**/*', '!src/dist/min/**'],
			shopify: ['shopify/assets/*.css', 'shopify/assets/*.js'],
			parallax: ['parallax/assets/*.css', 'parallax/assets/*.js'],
		},
	},
	assets: {
		vids: {
			ff: 'ffmpeg',
		},
		imgs: {
			logo: 'src/assets/img/logo/*.{JPG,jpg,png,gif,svg}',
			jpg: 'src/assets/img/jpg/*.{JPG,jpg}',
			png: 'src/assets/img/png/*.png',
			svg: 'src/assets/img/svg/*.svg',
			gif: 'src/assets/img/gif/*.gif',
		},
	},
	directories: {
		node: 'state/stage/NPM-' + timeDate,
		nodezip: 'NPM-' + timeDate + '.zip',
		des: 'state/stage/DES-' + timeDate,
		deszip: 'DES-' + timeDate + '.zip',
		shop: 'state/stage/THEME-V00-' + timeDate,
		shopzip: 'THEME-V00-' + timeDate + '.zip',
		arc: 'state/stage/DES-ARCHIVE-' + timeDate,
		arczip: 'DES-ARCHIVE-' + timeDate + '.zip',
		back: 'F:/Mithrasatori/Desmond/BACKUP-' + timeDate,
	},
	shell: {
		publish: 'cd package && npm publish',
		install: 'npm install -f --save-dev --no-audit @seerseven/desmond@latest',
		login: 'shopify login --store seerseven.myshopify.com',
		serve: 'cd shopify && shopify theme serve',
		unpublished: 'cd shopify && shopify theme push --unpublished',
		pull: 'cd shopify && echo y && echo y | shopify theme pull',
		push: 'cd shopify && echo y && echo y | shopify theme push',
		cli: 'gem update shopify-cli',
	},
	colors: {
		sass: '#e17eb0',
		dsass: '#bf4080',
		rem: '#fd2169',
		drem: '#550c24',
		canvas: '#b7bacf',
		dcanvas: '#959cd5',
		vendor: '#d5b695',
		dvendor: '#dba66c',
		bump2: '#e95724',
		dbump2: '#933210',
		bump1: '#92d025',
		dbump1: '#6d9d18',
		shopify: '#28ef28',
		dshopify: '#24b724',
		shopjs: '#39a75d',
		dshopjs: '#1a502c',
		build: '#d39f00',
		buildl: '#ffc412',
		dbuild: '#c39508',
		jquery: '#779295',
		djquery: '#48595b',
		libjs: '#5aa8be',
		dlibjs: '#86d9e2',
		corejs: '#3763c7',
		dcorejs: '#1246bc',
		mdb: '#7828e9',
		mdbl: '#935be2',
		mdbjs: '#9528e9',
		dmdbjs: '#7615c2',
		note: '#d1cfcf',
		notel: '#e8e6e6',
		theme: '#38c9e3',
		themel: '#35daf8',
		themejs: '#e3459e',
		dthemejs: '#c43b88',
		concat: '#c43b88',
		ugly: '#f1a124',
		dugly: '#ab731c',
		redsh: '#b80000',
		red: '#e0334c',
		dredl: '#812634',
		redl: '#ca5465',
		dred: '#9b0d21',
		purp: '#7b5be2',
		dpurp: '#2b0f6b',
		git1: '#ac2cb3',
		dgit1: '#421166',
		git2: '#f560cf',
		dgit2: '#721181',
		bump: '#1cb1dc',
		dblue: '#135366',
		blue: '#1cb1dc',
		lblue: '#1bb7ff',
		ojay: '#fd802d',
		dojay: '#7c3e14',
		app: '#d3b352',
		npm: '#fd2169',
		arc: '#c26912',
		shop: '#13af73',
		teal: '#13af73',
		lteal: '#30d686',
		dteal: '#1d6d47',
		mods: '#fd214a',
		dmods: '#6a0c1e',
		libs: '#cf3b8e',
		dlibs: '#5d1a40',
		pink: '#fd2169',
		dpink: '#6e1431',
		git: '#7952d3',
		dep: '#482d86',
		mill: '#d3b352',
		yell: '#d3b352',
		dyell: '#795e0e',
		green: '#197f28',
		text: '#00a2ff',
		grey: '#7e7e7e',
		dgrey: '#575758',
		black: '#000000',
		dark: '#1a2122',
		blk: '#000000',
		mith: '#ffffff',
	},
	variables: {
		border: '-------------------------------------------------------',
	},
	plugins: {
		progstream: require('progress-stream'),
		progress: require('cli-progress'),
		colors: require('ansi-colors'),
		chalk: require('chalk'),
		multi: require('gulp-multi-dest'),
		bump: require('gulp-bump'),
		zip: require('gulp-zip'),
		git: require('gulp-git'),
		push: require('gulp-git-push'),
		ignore: require('gulp-gitignore'),
		plum: require('gulp-plumber'),
		clean: require('gulp-clean'),
		wait: require('gulp-wait'),
		img: require('gulp-imagemin'),
		gendex: require('gulp-filelist')('_index.scss', {
			destRowTemplate: f.formatter,
			flatten: true,
			removeExtensions: true,
		}),
		filelist: require('gulp-filelist')('filelist.json'),
		shell: require('gulp-shell'),
		prompt: require('gulp-prompt'),
		sass: require('gulp-sass')(require('sass')),
		rname: require('gulp-rename'),
		concat: require('gulp-concat'),
		uglify: require('gulp-uglify'),
		nano: require('gulp-cssnano'),
		post: require('gulp-postcss'),
		conc: require('gulp-concat-css'),
		notify: require('gulp-notify'),
		noop: require('gulp-noop'),
		fs: require('fs'),
		perf: require('perf_hooks'),
		strip: require('gulp-remove-logging'),
		log: require('fancy-log'),
		opts: {
			bump: {
				type: 'patch',
			},
			min: {
				suffix: '.min',
			},
			expand: {
				outputStyle: 'expanded',
			},
			schema: {
				basename: 'sche-ma',
				extname: '.scss',
			},
			scss: {
				extname: '.scss',
			},
			css: {
				extname: '.css',
			},
			cts: {
				prefix: '_',
				extname: '.scss',
			},
			json: {
				basename: 'filelist',
				extname: '.json',
			},
			args: {
				args: '-m "initial commit"',
				disableMessageRequirement: true,
			},
			empty: {
				allowEmpty: true,
			},
			descss: 'desmond.css',
			desjs: 'desmond.js',
			query: 'query.js',
			canvas: 'canvas.js',
			vendor: 'vendor.js',
			mdb: 'mdb.js',
			libs: 'libs.js',
			core: 'core.js',
			concat: 'concat.js',
		},
	},
};
