module.exports = {
	pkg: './package.json',
	paths: {
		input: {
			app: './',
			shopify: 'src/build/shopify/shopify.css',
			mdb: 'src/build/vendors/mdb.css',
			notion: 'src/build/vendors/notion.css',
			theme: 'src/build/theme/theme.css',
			build: ['src/dist/shopify.css', 'src/dist/mdb.css', 'src/dist/theme.css'],
			cleancss: [
				'shopify/assets/*.css',
				'!shopify/assets/*.js',
				'!shopify/assets/desmond.css',
				'!shopify/assets/desmond.min.css',
			],
		},
		output: {
			end: 'end',
			app: './',
			dist: 'src/dist',
			parallax: 'parallax/assets',
			shopify: 'shopify/assets',
			multi: ['src/dist', 'shopify/assets'],
			pro: ['parallax/assets', 'shopify/assets'],
		},
	},
	colors: {
		shopify: '#28ef28',
		dshopify: '#24b724',
		build: '#d39f00',
		buildl: '#ffc412',
		mdb: '#7828e9',
		mdbl: '#935be2',
		note: '#d1cfcf',
		notel: '#e8e6e6',
		theme: '#38c9e3',
		themel: '#35daf8',
		concat: '#c43b88',
		red: '#e0334c',
		dred: '#9b0d21',
		purp: '#7b5be2',
		dpurp: '#2b0f6b',
		bump: '#1cb1dc',
		dblue: '#135366',
		blue: '#1cb1dc',
		ojay: '#fd802d',
		dojay: '#7c3e14',
		app: '#d3b352',
		npm: '#fd2169',
		arc: '#c26912',
		shop: '#13af73',
		teal: '#13af73',
		lteal: '#30d686',
		dteal: '#1d6d47',
		pink: '#fd2169',
		dpink: '#550c24',
		git: '#7952d3',
		dep: '#2b0f6b',
		mill: '#d3b352',
		yell: '#d3b352',
		dyell: '#795e0e',
		text: '#00a2ff',
		grey: '#7e7e7e',
		dgrey: '#575758',
		black: '#000000',
		dark: '#1a2122',
		blk: '#000000',
		mith: '#ffffff',
	},
	variables: {
		border: '-------------------------------------------------------',
	},

	plugins: {
		progstream: require('progress-stream'),
		progress: require('cli-progress'),
		colors: require('ansi-colors'),
		chalk: require('chalk'),
		multi: require('gulp-multi-dest'),
		bump: require('gulp-bump'),
		zip: require('gulp-zip'),
		git: require('gulp-git'),
		push: require('gulp-git-push'),
		ignore: require('gulp-gitignore'),
		plum: require('gulp-plumber'),
		clean: require('gulp-clean'),
		wait: require('gulp-wait'),
		img: require('gulp-imagemin'),
		shell: require('gulp-shell'),
		prompt: require('gulp-prompt'),
		sass: require('gulp-sass')(require('sass')),
		rname: require('gulp-rename'),
		concat: require('gulp-concat'),
		uglify: require('gulp-uglify'),
		nano: require('gulp-cssnano'),
		post: require('gulp-postcss'),
		conc: require('gulp-concat-css'),
		notify: require('gulp-notify'),
		noop: require('gulp-noop'),
		fs: require('fs'),
		perf: require('perf_hooks'),
		strip: require('gulp-remove-logging'),
		log: require('fancy-log'),
		opts: {
			bump: {
				type: 'patch',
			},
			min: {
				suffix: '.min',
			},
			conc: 'desmond.css',
		},
	},
};
